name: PROD Ružomberok Deploy

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod_ruzomberok
      environment_url: https://ruzomberok.odkazprestarostu.sk

    secrets: inherit
